
---
include: 

  - board: nice_nano_v2
    shield: lily58_left 
    artifact-name: lily58_left oled_adapter_pro_micro_128x64
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: lily58_right
    artifact-name: lily58_right oled_adapter_pro_micro_128x64
